In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [13]:
original_data = np.random.exponential(size=[10,3],scale=10.0)
original_data

array([[ 23.09465332,   9.37271555,   2.49990726],
       [  0.90646725,   0.13965637,   1.5442003 ],
       [  9.53730835,  29.92871677,   3.57465573],
       [ 15.44032183,   8.37597913,   7.09736596],
       [ 19.80368442,  12.68144182,   9.47338561],
       [ 11.17772945,   6.38714782,  10.74875059],
       [  8.02546952,   6.1393666 ,   3.47383203],
       [  2.04319472,   1.03307387,  15.73662193],
       [ 16.45328545,   9.98345185,  15.40181823],
       [ 12.42381646,  24.40808429,   3.80433254]])

In [18]:
standardizer = StandardScaler().fit(original_data)
standardizer.mean_,standardizer.scale_

(array([ 11.89059308,  10.84496341,   7.33548702]),
 array([ 6.78571015,  9.01896712,  5.00369427]))

In [20]:
std_data = standardizer.transform(original_data)
std_data

array([[ 1.65112567, -0.16323908, -0.96640192],
       [-1.61871427, -1.18697706, -1.15740219],
       [-0.34680007,  2.11595775, -0.75161093],
       [ 0.52311824, -0.27375466, -0.04758905],
       [ 1.16614049,  0.20362403,  0.42726403],
       [-0.10505365, -0.49427119,  0.68214871],
       [-0.5695975 , -0.52174454, -0.77176078],
       [-1.45119643, -1.08791721,  1.67898646],
       [ 0.67239718, -0.0955222 ,  1.61207515],
       [ 0.07858034,  1.50384414, -0.70570948]])

In [21]:
original_data_destandarized = standardizer.inverse_transform(std_data)
original_data_destandarized

array([[ 23.09465332,   9.37271555,   2.49990726],
       [  0.90646725,   0.13965637,   1.5442003 ],
       [  9.53730835,  29.92871677,   3.57465573],
       [ 15.44032183,   8.37597913,   7.09736596],
       [ 19.80368442,  12.68144182,   9.47338561],
       [ 11.17772945,   6.38714782,  10.74875059],
       [  8.02546952,   6.1393666 ,   3.47383203],
       [  2.04319472,   1.03307387,  15.73662193],
       [ 16.45328545,   9.98345185,  15.40181823],
       [ 12.42381646,  24.40808429,   3.80433254]])