In [1]:
import tensorflow as tf
import numpy as np

In [2]:
NUM_OBSERVATIONS = 3
NUM_FEATURES = 7
NUM_CLASSES = 1

In [13]:
categorical_values = np.array(['Foo','bar','values']) #For one observation
lookup, labeledValues = np.unique(categorical_values, return_inverse=True)

labeledValues

array([0, 1, 2], dtype=int64)

In [15]:
oneHotValues = tf.one_hot(labeledValues,depth=NUM_FEATURES)
oneHotValues

<tf.Tensor 'one_hot_3:0' shape=(3, 7) dtype=float32>

In [16]:
x_categorical = oneHotValues

weights = tf.Variable(tf.truncated_normal([NUM_FEATURES,NUM_CLASSES]),dtype=tf.float32)
bias = tf.Variable([NUM_CLASSES],dtype=tf.float32)

l2 = tf.add(tf.matmul(x_categorical,weights),bias)

In [21]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    _l2,_oneHotValues = sess.run([l2,oneHotValues])

In [22]:
_oneHotValues

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.]], dtype=float32)

In [23]:
_l2

array([[ 0.80529004],
       [ 1.0421437 ],
       [-0.52445245]], dtype=float32)