In [12]:
import numpy as np
import math

In [37]:
def ranged_arr(n):
    #Creates an array of the numbers from 0 up to that inputted integer 
    ranged_arr = np.arange(0,n+1)

    #Reshapes it to be the largest n * n array that it could be
    
    #Find the largest dim
    largest_dim = math.floor(math.sqrt(n+1))
    #Find the size of the array that will be reshaped
    last_index = largest_dim**2
    #Take the slice of the original array that could be reshaped
    fitted_ranged_arr = ranged_arr[:last_index]
    #Finally, reshape it!
    reshaped_range_arr = fitted_ranged_arr.reshape((largest_dim,largest_dim))
    
    #Return everything, so you can check the steps
    return ranged_arr,largest_dim,fitted_ranged_arr,reshaped_range_arr

In [38]:
test(1)

(array([0, 1]), 1, array([0]), array([[0]]))

In [39]:
test(2)

(array([0, 1, 2]), 1, array([0]), array([[0]]))

In [40]:
test(3)

(array([0, 1, 2, 3]), 1, array([0]), array([[0]]))

In [41]:
test(4)

(array([0, 1, 2, 3, 4]), 2, array([0, 1, 2, 3]), array([[0, 1],
        [2, 3]]))

In [42]:
test(5)

(array([0, 1, 2, 3, 4, 5]), 2, array([0, 1, 2, 3]), array([[0, 1],
        [2, 3]]))

In [43]:
test(10)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 3,
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [44]:
test(90)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90]),
 9,
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41,

In [45]:
test(1200)

(array([   0,    1,    2, ..., 1198, 1199, 1200]),
 34,
 array([   0,    1,    2, ..., 1153, 1154, 1155]),
 array([[   0,    1,    2, ...,   31,   32,   33],
        [  34,   35,   36, ...,   65,   66,   67],
        [  68,   69,   70, ...,   99,  100,  101],
        ..., 
        [1054, 1055, 1056, ..., 1085, 1086, 1087],
        [1088, 1089, 1090, ..., 1119, 1120, 1121],
        [1122, 1123, 1124, ..., 1153, 1154, 1155]]))